config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
  get 'books/index'
  end

  namespace :backoffice do
  get 'categories/index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'book', to: 'home#book'

    namespace :profile do
      resources :dashboard, only: [:index, :edit, :update]
    end
  end

  get 'admin', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :books, except: [:show, :destroy]
    resources :admins, except: [:show, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :leitors
  root 'site/home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :leitor
  validates_presence_of :name, :isbn, :author, :pages, :condition

  has_attached_file :image, styles: { medium: "170x240>", thumb: "85x120>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/leitor.rb
class Leitor < ActiveRecord::Base
	has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_attached_file :avatar, styles: { medium: "180x180>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected 

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
  	else
  		"application"
  	end
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
	before_action :set_admin, only: [:edit, :update]

  def index
  	@admins = Admin.all
  end
end

app/controllers/backoffice/books_controller.rb
class Backoffice::BooksController < BackofficeController
	before_action :set_book, only: [:edit, :update]

  def index
  	@books = Book.all
  end
  def new
  	@book = Book.new
  end
  def create
  	@book = Book.new(params_book)
  	if @book.save
  		redirect_to backoffice_books_index_path, notice: "O Livro '#{@book.name}' foi criado!"
  	else
  		render :new
  	end
  end
  def edit
  end
  def update
  	if @book.update(params_book)
  		redirect_to backoffice_books_index_path, notice: "O Livro '#{@book.name}' foi atualizado!"
  	else
  		render :edit
  	end
  end

  private
  def set_book
  	@book = Book.find(params[:id])
  end

  def params_book
  	params.require(:book).permit(:isbn, :name, :author, :pages, :condition)
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  def index
  	@categories = Category.all
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
  layout "backoffice"
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"
  def index
  	@books = Book.limit(100).order(created_at: :desc)
  end
end

app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < ApplicationController
	before_action :set_book, only: [:edit]
	layout "site"
	def index
		@books = Book.where(leitor_id: current_leitor.id)
	end
	def edit
	end

	private
	def set_book
		@book = Book.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/books_helper.rb
module Backoffice::BooksHelper
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/index.html.erb
<div id="wrapper">
  <!-- Page Content -->
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">
          	Administradores
          </h1>
            <div class="panel-body">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Email</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @admins.each do | admin | %>
                    <tr>
                      <td style="width: 10%;"><%= admin.id %></td>
                      <td><%= admin.email %></td>
                    </tr>
                  </tbody>
                  <% end %>
                </table>
            </div>
            <!-- /.table-responsive -->
          </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
    </div>
  </div>
</div>

app/views/backoffice/books/edit.html.erb
<%= render partial: "backoffice/books/form_partial/form", locals: {action: "Editando Livro"} %>

app/views/backoffice/books/index.html.erb
<div id="wrapper">
  <!-- Page Content -->
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">
          	Livros
          	<%= link_to new_backoffice_book_path, class:"btn btn-success btn-circle pull-right" do %>
          		<i class="fa fa-plus"></i>
     				<% end %>
          </h1>
            <div class="panel-body">
              <div class="table-responsive">
              	<% if notice %>
              		<div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <%= notice %>
                  </div>
              	<% end %>
                <table class="table">
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @books.each do | book | %>
                    <tr>
                      <td><%= book.name %></td>
                      <td style="width: 10%;">
                      	<%= link_to edit_backoffice_book_path(book), class:"btn btn-info btn-circle" do %>
                      		<i class="fa fa-edit"></i>
                      	<% end %>
                      	<button type="button" class="btn btn-danger btn-circle disabled"><i class="fa fa-times"></i></button>
                      </td>
                    </tr>
                  </tbody>
                  <% end %>
                </table>
            </div>
            <!-- /.table-responsive -->
          </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
    </div>
  </div>
</div>

app/views/backoffice/books/new.html.erb
<%= render partial: "backoffice/books/form_partial/form", locals: {action: "Novo Livro"} %>

app/views/backoffice/categories/index.html.erb
<div id="wrapper">
  <!-- Page Content -->
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">Categorias</h1>
            <div class="panel-body">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Categoria</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @categories.each do | category | %>
                    <tr>
                      <td style="width: 5%;"><%= category.id %></td>
                      <td><%= category.name %></td>
                      <td style="width: 8%;"><button type="button" class="btn btn-info">Editar</button></td>
                    </tr>
                  </tbody>
                  <% end %>
                </table>
            </div>
            <!-- /.table-responsive -->
          </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
    </div>
  </div>
</div>

app/views/backoffice/dashboard/index.html.erb
<div id="wrapper">
  <!-- Page Content -->
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">Dashboard</h1>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
    </div>
  </div>
</div>

app/views/layouts/backoffice_partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html">Admin - São Jerônimo</a>
  </div>
  <!-- /.navbar-header -->
  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <!-- /.dropdown -->
      <p><%= current_admin.email %></p>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <%= link_to destroy_admin_session_path, method: :delete do %>
            <i class="fa fa-sign-out fa-fw"></i> Sair
          <%end%>
        </ul>
        <!-- /.dropdown-user -->
      </li>
      <!-- /.dropdown -->
  	</ul>
  	<!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li>
            <%= link_to backoffice_books_index_path do %>
              <i class="fa fa-book"></i> Livros
            <% end %>
          </li>
          <li>
            <%= link_to backoffice_admins_path do %>
              <i class="fa fa-users"></i> Administradores
            <% end %>
          </li>
        </ul>
      </div>
      <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

app/views/layouts/site_partials/_content_left.html.erb
<div class="content-left">
	<div class="menu-left">
		<% unless leitor_signed_in? %>
		<%= link_to "Login", new_leitor_session_path, style: "margin: 20px;" %>
		<%= link_to "Cadastro", new_leitor_registration_path, style: "margin: 20px;" %>

		<% else %>
		<%= image_tag current_leitor.avatar.url(:medium), :class => "card-img-top" %>
		<div class="menu-left">
			<h4 class="name"><%=current_leitor.name%></h4>
			<h5 class="id text-muted">ID: <%=current_leitor.id%></h5>
			<ul>
				<li><%= link_to "Minha conta", site_profile_dashboard_index_path %></li>
			</ul>
			<%= link_to "Sair", destroy_leitor_session_path, method: :delete %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/site_partials/_footer.html.erb
<footer>
	<div class="row">
		<h2 class="col-sm-3 logo">São Jerônimo</h2>
		<div class="col-sm-3 institucional">
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</p>
		</div>
		<div class="col-sm-3 mapa">
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">Livros</a></li>
				<li><a href="#">Autores</a></li>
				<li><a href="#">Leitores</a></li>
			</ul>
		</div>
		<div class="col-sm-3 social-media">
			<ul>
				<li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
				<li><a href="#"><i class="fa fa-instagram"></i></a></li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/site_partials/_navbar.html.erb
<nav>
	<%= link_to "Biblioteca São Jerônimo", site_home_path, class:"navbar-brand logo active"  %>
	<div class="search-container">
	  <form action="/action_page.php">
	    <input type="text" placeholder="Pesquisar" name="search">
	    <button type="submit"><i class="fa fa-search"></i></button>
	  </form>
	</div>
</nav>

app/views/leitors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/site/home/book.html.erb
<style type="text/css">
	.book-container{
		padding: 10px 15px;
		display: block;
	}
	.request-container{
		padding: 10px 15px;
		display: inline-block;
		text-align: center;
	}
	.front-cover{
		float: left;
		margin: 10px 15px;
		border-radius: 5%;
	}
	.info{
		margin-left: 10px;
	}
	.btn-borrow{
		color: #EBF9E8;
		background-color: #33673B;
		padding: 10px;
		margin-top: 15px;
		margin-bottom: 15px;
	}
	.btn-borrow:hover{
		color: #EBF9E8;
		background-color: #57875E;
	}
	.btn-return{
		color: #EBF9E8;
		background-color: #545454;
		padding: 10px;
	}
	.btn-return:hover{
		color: #EBF9E8;
		background-color: #7F7171;
	}
</style>
<div class="content-right">
	<div class="book-container">
		<img class="front-cover" src="https://via.placeholder.com/170x240?text=livro" alt="Capa do livro">
		<h2>Nome do livro</h2>
		<div class="info row">
			<div class="col-sm">
				<p class="text-muted">Autor</p>
				<p>Dono</p>
			</div>
			<div class="col-sm">
				<p class="text-muted">Estado</p>
				<p class="text-muted">Número de páginas</p>
			</div>
		</div>
	</div>
	<div class="request-container">
		<button class="btn btn-borrow">Pedir emprestado</button>
		<button class="btn btn-return">Devolvido ao Dono</button>
	</div>
</div>

app/views/site/home/index.html.erb
<div class="content-right">
	<div class="best">
		<h2>Livros disponíveis</h2>
		<hr>
		<div class="row">
			<% @books.each do | book | %>
				<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
			    <div class="card h-100">
			      <%= image_tag book.image.url(:thumb), :class => "card-img-top" %>
			      <div class="card-body">
			      	<h4 class="card-title"><%= link_to "#{book.name}", site_book_path %></h4>
			        <p><%= book.author %></p>
			        <p class="text-muted"><%= book.isbn %></p>
			        <p class="text-muted"><%= book.leitor.name %></p>
			      </div>
			    </div>
			  </div>
			<% end %>
		  </div>
		</div>
	</div>
	<!-- Fim últimos adicionados -->
	<hr>
</div>

app/views/site/profile/dashboard/edit.html.erb
<h1>Edit</h1>

<%= form_for([:site, :profile, :dashboard, @book]) do |f| %>
	<div class="form-group">
		<label>Nome</label>
		<%= f.text_field :name, class:"form-control", placeholder:"Nome" %> 
	</div>
<% end %>

app/views/site/profile/dashboard/index.html.erb
<div class="content-right">
	<div class="best">
		<h2>Minha conta</h2>
		<hr>
		<div class="row">
			<table class="table table-hover">
				<thead>
					<th>ID</th>
					<th><strong>Livro</strong></th>
					<th style="width: 3%;"></th>
					<th style="width: 3%;"></th>

				</thead>
				<tbody>
					<% @books.each do | book | %>
					<tr>
						<td><%= book.id %></td>
						<td><%= book.name %></td>
						<td><%= link_to edit_site_profile_dashboard_path(book.id), class:"btn btn-info" do %> 
								<i class="fa fa-edit"></i>
								<% end %></td>
						<td><button class="btn btn-danger"><i class="fa fa-trash"></i></button></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<!-- Fim últimos adicionados -->
	<hr>
</div>